IMAGE_NAME = "bento/ubuntu-16.04"

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.box = IMAGE_NAME
  config.vm.network "public_network", ip: "192.168.15.17"
end
