IMAGE_NAME = "bento/ubuntu-16.04"

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end


  config.vm.define "k8s-master" do |master|
    master.vm.box = IMAGE_NAME
    config.vm.network "public_network", ip: "192.168.15.17"
    master.vm.hostname = "k8s-master"
#    master.vm.provision "ansible" do |ansible|
#        ansible.playbook = "kubernetes-setup/master-playbook.yml"
#        ansible.extra_vars = {
#            node_ip: "192.168.50.10",
#        }
#    end
end