---
  - hosts: #master
    become: yes
    gather_facts: false
    tasks:
      - name: "CMD - Get join command"
        shell: kubeadm token create --print-join-command
        register: join_command_raw
      
      - name: "SET - Set join command"
        set_fact:
          join_comand: "{{ join_command_raw.stdout_lines[0] }}"
  
  - hosts: #worker
    become: yes
    tasks:
      - name: "CMD - Join cluster"
        shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
        args:
          chdir: $HOME
          creates: node_joined.txt