---
  - hosts: all
    vars:
      - devops_password: suasenha
        ansible_python_interpreter: "/usr/bin/env python3"
    gather_facts: no
    remote_user: infra
    become: true

    tasks:
      - name: "USER - Add a new user named devops"
        user:
          name: devops
          shell: /bin/bash
          password: "{{devops_password}}"

      - name: "COPY - Add devops user to the sudoers"
        copy:
          dest: "/etc/sudoers.d/devops"
          content: "devops ALL=(ALL) NOPASSWD: ALL"
          
      - name: "SSH - Deploy SSH Key"
        authorized_key:
          user: devops
          key: "{{ lookup('file', '/home/devops/.ssh/id_rsa.pub')}}"
          state: present

      - name: "LNFILE - Disable passwd auth"
        lineinfile:
          dest: "/etc/ssh/sshd_config"
          regexp: '^PasswordAuthentication'
          line: 'PasswordAuthentication no'
          state: present
          backup: yes

      - name: "LNFILE - Disable root login"
        lineinfile:
          dest: "/etc/ssh/sshd_config"
          regexp: '^PermitRootLogin'
          line: 'PermitRootLogin no'
          state: present
          backup: yes          
        notify:
          - restart ssh
    handlers:
      - name: restart ssh
        service:
          name: sshd
          state: restarted