---
  - hosts: all
    gather_facts: no
    remote_user: devops
    become: true
    vars:
      ansible_python_interpreter: "/usr/bin/env python3"
      
    tasks:
     - name: "APT - Add Docker  GPG key"
       apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present

     - name: "APT - Add Docker repository"
       apt_repository:
         repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
         state: present
         filename: docker

     - name: "APT - Install misc packages"
       apt:
         name: ["aptitude", "apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
         update_cache: yes

     - name: "APT - Install 'docker-ce'"
       apt:
         name: "docker-ce=18.06.2~ce~3-0~ubuntu"
         update_cache: yes

     - name: "FILE - Create daemon file"
       copy:
         dest: "/etc/docker/daemon.json" 
         content: "{{ lookup('file', '/home/devops/docker/daemon.json')}}"
     
     - name: "FILE - Create service folder"
       file:
         path: "/etc/systemd/system/docker.service.d"
         state: directory
       notify:
         - restart docker

    handlers:
      - name: restart docker
        systemd:
          state: restarted
          name: docker
          daemon_reload: yes