---
- name: "APT - Install Kubernetes CTL binaries"
  become: yes
  apt:
    name: kubectl=1.15.0-00
    state: present
    force: yes 

- name: "CMD - Initialize K8s cluster using kubeadm"
  become: yes
  shell: >
    kubeadm init 
    --node-name {{ kubernetes_master_name }} 
    --pod-network-cidr={{ kubernetes_pod_network_cidr }} 
    --kubernetes-version {{ kubernetes_version_kubeadm }}
    --ignore-preflight-errors={{ kubernetes_ignore_preflight_errors }} >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: "FILE - Create .kube directory"
  become: yes
  file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: "COPY - Copy admin.conf to user's kube config"
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: yes
    owner: devops

- name: "CMD - Install calico pod network"
  become: yes
  shell: kubectl apply -f {{ kubernetes_calico_manifest_file }} >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: "CMD - Allow pods on master node (if configured)."
  shell: "kubectl taint nodes --all node-role.kubernetes.io/master- >> pod_allow_setup.txt"
  args:
    chdir: $HOME
    creates:  pod_allow_setup.txt
  when:
    - kubernetes_allow_pods_on_master | bool